name: _job_upload

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      name:
        required: true
        type: string

permissions:
  contents: read

jobs:
  upload:
    permissions:
      contents: write
    timeout-minutes: 15
    name: Upload ${{ inputs.name }}
    strategy:
      matrix:
        include:
          - file: ${{ inputs.name }}.tar.gz
          - file: ${{ inputs.name }}.sha512sum
          - file: ${{ inputs.name }}.tar.gz.sha256

    runs-on: ubuntu-24.04

    steps:
      - name: Verify release exists
        run: |
          gh release view "${{ inputs.version }}" \
            --repo "${{ github.server_url }}/${{ github.repository }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download ${{ matrix.file }} artifact
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: ${{ matrix.file }}

      - name: Upload ${{ matrix.file }} to release
        shell: bash
        run: >-
          gh
          --repo "${{ github.server_url }}/${{ github.repository }}"
          release upload
          ${{ inputs.version }}
          ${{ matrix.file }}
          --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
